AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/ParameterLists:
  CountKeywordArgs: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error
